#!/bin/bash
source "$(dirname $0)/../ministore/functions.sh"

CMD="$1"

case "$CMD" in

	get)
		STDIN=$(read_stdin)

		HOST=$(get_var "$STDIN" "host") 
		USER=$(get_var "$STDIN" "username") 

		ID="git:$HOST:$USER"

		PASSWD=$(get_passwd "$ID")

		if [ -n "$PASSWD" ]
		then
			echo "password=$PASSWD"
		fi
		;;

	store)
		;;

	erase)
		;;

	*)
		;;

esac
