#!/bin/bash
source "$(dirname $0)/../ministore/functions.sh"
source "$(dirname $0)/../ministore/git-functions.sh"

COMMAND="$1"

# Parse standard input from git
SAVED_IFS="${IFS}"
IFS=''

STDIN="$(read_stdin)"

HOST=$(get_var "${STDIN}" "host")
[[ -n "${HOST}" ]] || exit

USERNAME=$(get_var "${STDIN}" "username")
[[ -n "${USERNAME}" ]] || exit

PASSWORD=$(get_var "${STDIN}" "password")

IFS="${SAVED_IFS}"

# Do the stuff
KEY_PATH="git/${HOST}/${USERNAME}"

case "${COMMAND}" in

	erase)
		del_key "${KEY_PATH}"
		;;

	get)
		PASSWORD=$(get_key "${KEY_PATH}")

		[[ -n "${PASSWORD}" ]] || exit

		echo "password=${PASSWORD}"
		;;

	store)

		[[ -n "${PASSWORD}" ]] || exit

		set_key "${KEY_PATH}" "${PASSWORD}"
		;;

	*)
		;;

esac

# See specs of git-credentials at: https://git-scm.com/docs/gitcredentials
