#!/bin/bash
source "$(dirname $0)/../lib/ministore/functions.sh"

COMMAND="$1"
KEY_PATH="$2"
KEY_VALUE="$3"

assert_key_path() {
	if [ -z "${KEY_PATH}" ]
	then
		echo "ministore: no key path provided"
		exit 2
	fi
}

assert_key_value() {
	if [ -z "${KEY_VALUE}" ]
	then
		echo "ministore: no key value provided"
		exit 3
	fi
}

case "${COMMAND}" in

	del)
		assert_key_path

		del_key "${KEY_PATH}"
		;;

	get)
		assert_key_path

		get_key "${KEY_PATH}"
		;;

	list)
		list_keys
		;;

	set)
		assert_key_path
		assert_key_value

		set_key "${KEY_PATH}" "${KEY_VALUE}"
		;;

	type)
		assert_key_path

		set_typed_key "${KEY_PATH}"
		;;

	*)
		cat <<EOF

Usage:

    ministore <command> ...


Valid commands:

    list

        List the paths of all stored keys.


    get <key path>

        Prints a key value.


    set <key path> <key value>

        Sets the value of a key.

        Beware of shell history when using this command since the key value
        might be cached in persistent storage. Use 'type' when possible.


    type <key path>

        Prompts the user for the value of a key.


    del <key path>

        Deletes a key.


EOF

		exit 1
		;;

esac
